# Generated by Django 4.2.7 on 2024-01-19 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0001_initial"),
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="customers.customer"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="university.student"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="study_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="university.studygroup"
            ),
        ),
    ]
