# Generated by Django 5.0.1 on 2024-06-15 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContractStatus",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
