# Generated by Django 4.2.7 on 2024-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("phone_number", models.IntegerField()),
                ("passport_number", models.IntegerField()),
                ("passport_issuance", models.CharField(max_length=300)),
                ("passport_issue_date", models.DateField()),
                ("passport_division_code", models.CharField(max_length=7)),
                ("passport_registration", models.CharField(max_length=500)),
            ],
        ),
    ]
