# Generated by Django 5.0.1 on 2024-06-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_alter_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=19),
        ),
    ]
