# Generated by Django 5.0.1 on 2024-06-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
