# Generated by Django 5.0.1 on 2024-06-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0002_discipline_discipline_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=32),
        ),
    ]
