# Generated by Django 5.0.1 on 2024-06-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0004_studygroup_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studygroup",
            name="grade",
            field=models.IntegerField(),
        ),
    ]
